export const puzzle = {
  rows: 8,
  cols: 7,
  grid: [
    [
      { number: 1, solution: "N" },
      { solution: "I" },
      { solution: "H" },
      { isBlack: true },
      { number: 4, solution: "W" },
      { number: 5, solution: "W" },
      { number: 6, solution: "I" },
    ],
    [
      { number: 7, solution: "B" },
      { solution: "R" },
      { solution: "A" },
      { isBlack: true },
      { number: 8, solution: "H" },
      { solution: "A" },
      { solution: "N" },
    ],
    [
      { number: 9, solution: "C" },
      { solution: "O" },
      { solution: "N" },
      { number: 10, solution: "F" },
      { solution: "I" },
      { solution: "R" },
      { solution: "M" },
    ],
    [
      { isBlack: true },
      { number: 11, solution: "Q" },
      { solution: "U" },
      { solution: "I" },
      { solution: "Z" },
      { solution: "M" },
      { solution: "E" },
    ],
    [
      { number: 12, solution: "J" },
      { solution: "U" },
      { solution: "K" },
      { solution: "E" },
      { solution: "B" },
      { solution: "O" },
      { solution: "X" },
    ],
    [
      { number: 13, solution: "A" },
      { solution: "O" },
      { solution: "K" },
      { isBlack: true },
      { number: 14, solution: "A" },
      { solution: "V" },
      { solution: "I" },
    ],
    [
      { number: 15, solution: "V" },
      { solution: "I" },
      { solution: "A" },
      { isBlack: true },
      { number: 16, solution: "N" },
      { solution: "I" },
      { solution: "C" },
    ],
    [
      { number: 17, solution: "A" },
      { solution: "S" },
      { solution: "H" },
      { isBlack: true },
      { number: 18, solution: "G" },
      { solution: "E" },
      { solution: "O" },
    ],
  ],
  across: [
    {
      number: 1,
      clue: "Research org. that once employed Dr. Fauci",
      answer: "NIH",
    },
    {
      number: 4,
      clue: "Conflict ended on 11/11/1918, for short",
      answer: "WWI",
    },
    { number: 7, clue: "Garment with an underwire", answer: "BRA" },
    { number: 8, clue: "___ Solo of 'Star Wars'", answer: "HAN" },
    { number: 9, clue: "Verify the truth of", answer: "CONFIRM" },
    {
      number: 11,
      clue: "Student's request while preparing for a test",
      answer: "QUIZME",
    },
    {
      number: 12,
      clue: "Music player at a '50s-style diner",
      answer: "JUKEBOX",
    },
    { number: 13, clue: '"All good to go!"', answer: "AOK" },
    { number: 14, clue: "Prefix meaning 'bird' or 'flight'", answer: "AVI" },
    { number: 15, clue: "By way of", answer: "VIA" },
    { number: 16, clue: "Actor Cage,to fans", answer: "NIC" },
    { number: 17, clue: "Flecks from a campfire", answer: "ASH" },
    { number: 18, clue: "Nat ___ (TV channel)", answer: "GEO" },
  ],
  down: [
    { number: 1, clue: '"Saturday Night Live" network', answer: "NBC" },
    {
      number: 2,
      clue: "The Haudenosaunee Confederacy, by another name",
      answer: "IROQUOIS",
    },
    { number: 3, clue: "Eight-day Jewish holiday", answer: "HANUKKAH" },
    {
      number: 4,
      clue: "Sensationally successful, in older slang",
      answer: "WHIZBANG",
    },
    {
      number: 5,
      clue: '"Full Metal Jacket" or "Saving Private Ryan"',
      answer: "WARMOVIE",
    },
    {
      number: 6,
      clue: "Where Baja California is, as opposed to California",
      answer: "INMEXICO",
    },
    { number: 10, clue: "Fee, ___, foe, fum", answer: "FIE" },
    {
      number: 12,
      clue: "Coding language with a coffee cup logo",
      answer: "JAVA",
    },
  ],
};
